export const tasksAllData = [
  {
    id: 1,
    flagColor: "bg-red-600",
    title: "Incomplete",
    items: [
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
    ],
  },
  {
    id: 2,
    flagColor: "bg-blue-400",
    title: "To do",
    items: [
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
    ],
  },
  {
    id: 3,
    flagColor: "bg-yellow-400",
    title: "Doing",
    items: [
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
    ],
  },
  {
    id: 4,
    title: "Under Review",
    items: [
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
    ],
  },
  {
    id: 5,
    title: "Completed",
    items: [
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
    ],
  },
  {
    id: 6,
    title: "Something",
    items: [
      {
        id: 1,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
      {
        id: 2,
        clientName: "Client Name",
        clientImg: "/images/profile-img-1.jpg",
        developerName: "Developer Name",
        developerImg: "/images/profile-img-2.jpg",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, asperiores.",
        contributeImg1: "/images/profile-img-1.jpg",
        contributeImg2: "/images/profile-img-2.jpg",
        contributeCount: "10+",
        comment: "16",
        copy: "12",
        attachedData: [],
        date: "12-08-2022",
      },
    ],
  },
];
